# Generated by Django 5.0.6 on 2024-06-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_profile_location_profile_city_profile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
