# Generated by Django 5.0.6 on 2024-06-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_city_alter_profile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
